### ISSUE TITLE
Put all workbook hints in a different coloured box (see checklist)

### ISSUE THREAD

**Issue by jim-smith** [jim-smith/Artificial_Intelligence_1#11]
use a div or some such so that description of the task is separated from how to do it

**Comment by jim-smith** [comment]
- [ ] weeek1
- [ ] week2
- [ ] week3
- [ ] week4
- [ ] week 5
- [ ] week 6
- [ ] week 7
- [ ] week 8
- [ ] week 9
- [ ] week 10
- [ ] week 11
-

**Comment by NathanDuran** [comment]
Closing because this is being resolved by #22
